allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

blockExoticSubdeps: true

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - "@usehercules/*"

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

packages:
  - .
