packages:
  - .

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

blockExoticSubdeps: true

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@usehercules/*"
allowBuilds:
  esbuild: true
